nodeLinker: node-modules
pnpMode: "loose"

npmScopes:
  apptractive:
    npmAlwaysAuth: true
    npmAuthToken: "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"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
